import { FastifyInstance } from 'fastify'
import { z } from 'zod'
import { prisma } from '../db.js'
import { getAuthUser } from '../auth/getUser.js'
import { applyBalanceChange } from '../wallet/wallet.js'
const promoCreateSchema=z.object({code:z.string().min(2).max(32),amount:z.number().int().positive().max(10000000),maxUses:z.number().int().positive().max(100000).default(1)})
const promoRedeemSchema=z.object({code:z.string().min(2).max(32)})
function norm(code:string){return code.trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'')}
const WHEEL_SEGMENTS=[{amount:500,weight:30},{amount:1000,weight:25},{amount:2000,weight:18},{amount:3000,weight:12},{amount:5000,weight:8},{amount:7500,weight:4},{amount:10000,weight:2},{amount:25000,weight:1}]
const WHEEL_COOLDOWN_MS=24*60*60*1000
function pickWheelSegment(){ const total=WHEEL_SEGMENTS.reduce((s,x)=>s+x.weight,0); let r=Math.random()*total; for(let i=0;i<WHEEL_SEGMENTS.length;i++){ r-=WHEEL_SEGMENTS[i].weight; if(r<=0) return i } return WHEEL_SEGMENTS.length-1 }
export async function bonusRoutes(app:FastifyInstance){
 app.get('/wheel/status',{preHandler:[(app as any).authenticate]},async(req)=>{ const u=await getAuthUser(req); const last=await prisma.walletTransaction.findFirst({where:{userId:u.id,source:'wheel_spin'},orderBy:{createdAt:'desc'}}); if(!last) return {ready:true,nextAvailableAt:null}; const nextAt=new Date(last.createdAt.getTime()+WHEEL_COOLDOWN_MS); const ready=Date.now()>=nextAt.getTime(); return {ready,nextAvailableAt:nextAt.toISOString()} })
 app.post('/wheel',{preHandler:[(app as any).authenticate]},async(req,rep)=>{ const u=await getAuthUser(req); const last=await prisma.walletTransaction.findFirst({where:{userId:u.id,source:'wheel_spin'},orderBy:{createdAt:'desc'}}); if(last){ const nextAt=last.createdAt.getTime()+WHEEL_COOLDOWN_MS; if(Date.now()<nextAt) return rep.code(400).send({error:'Колесо ещё не готово',nextAvailableAt:new Date(nextAt).toISOString()}) } const idx=pickWheelSegment(); const amount=BigInt(WHEEL_SEGMENTS[idx].amount); const updated=await prisma.$transaction(async tx=>applyBalanceChange({tx,userId:u.id,amount,type:'BONUS',source:'wheel_spin',metadata:{segment:idx,prize:WHEEL_SEGMENTS[idx].amount}})); return {segment:idx,amount:Number(amount),balance:Number(updated.balance),nextAvailableAt:new Date(Date.now()+WHEEL_COOLDOWN_MS).toISOString()} })
 app.post('/daily',{preHandler:[(app as any).authenticate]},async(req,rep)=>{ const u=await getAuthUser(req); const dayStart=new Date(); dayStart.setHours(0,0,0,0); const old=await prisma.dailyBonus.findFirst({where:{userId:u.id,claimedAt:{gte:dayStart}}}); if(old) return rep.code(400).send({error:'Daily bonus already claimed'}); const amount=200n; const updated=await prisma.$transaction(async tx=>{ await tx.dailyBonus.create({data:{userId:u.id,amount}}); return applyBalanceChange({tx,userId:u.id,amount,type:'BONUS',source:'daily_bonus'}) }); return {amount:Number(amount),balance:Number(updated.balance)} })
 app.post('/promocode/create',{preHandler:[(app as any).authenticate]},async(req,rep)=>{ const u=await getAuthUser(req); const parsed=promoCreateSchema.safeParse(req.body); if(!parsed.success) return rep.code(400).send({error:'Введите код и сумму'}); const code=norm(parsed.data.code); if(!code) return rep.code(400).send({error:'Введите код промокода'}); const exists=await prisma.walletTransaction.findFirst({where:{source:'promo-create',metadata:{path:['code'],equals:code}} as any}); if(exists) return rep.code(400).send({error:'Такой промокод уже есть'}); const total=BigInt(parsed.data.amount*parsed.data.maxUses); await prisma.$transaction(async tx=>{ await applyBalanceChange({tx,userId:u.id,amount:-total,type:'ADMIN_ADJUSTMENT',source:'promo-create-reserve',metadata:{code,amount:parsed.data.amount,maxUses:parsed.data.maxUses}}); const fresh=await tx.user.findUniqueOrThrow({where:{id:u.id}}); await tx.walletTransaction.create({data:{userId:u.id,type:'ADMIN_ADJUSTMENT',amount:0n,balanceBefore:fresh.balance,balanceAfter:fresh.balance,source:'promo-create',metadata:{code,amount:parsed.data.amount,maxUses:parsed.data.maxUses,creatorId:u.id,creatorUsername:u.username,active:true}}}); }); return {code,amount:parsed.data.amount,maxUses:parsed.data.maxUses} })
 app.post('/promocode/redeem',{preHandler:[(app as any).authenticate]},async(req,rep)=>{ const u=await getAuthUser(req); const parsed=promoRedeemSchema.safeParse(req.body); if(!parsed.success) return rep.code(400).send({error:'Введите промокод'}); const code=norm(parsed.data.code); const promo=await prisma.walletTransaction.findFirst({where:{source:'promo-create',metadata:{path:['code'],equals:code}} as any,orderBy:{createdAt:'desc'}}); if(!promo) return rep.code(404).send({error:'Промокод не найден'}); const meta:any=promo.metadata||{}; const usedCount=await prisma.walletTransaction.count({where:{source:'promo-redeem',metadata:{path:['code'],equals:code}} as any}); if(usedCount >= (Number(meta.maxUses)||1)) return rep.code(400).send({error:'Лимит активаций закончился'}); const used=await prisma.walletTransaction.findFirst({where:{userId:u.id,source:'promo-redeem',metadata:{path:['code'],equals:code}} as any}); if(used) return rep.code(400).send({error:'Ты уже активировал этот промокод'}); const amount=BigInt(Number(meta.amount)||0); if(amount<=0n) return rep.code(400).send({error:'Промокод недействителен'}); const updated=await prisma.$transaction(async tx=>{ const fresh=await tx.user.findUniqueOrThrow({where:{id:u.id}}); await tx.walletTransaction.create({data:{userId:u.id,type:'BONUS',amount:0n,balanceBefore:fresh.balance,balanceAfter:fresh.balance,source:'promo-redeem',metadata:{code,promoId:promo.id}}}); return applyBalanceChange({tx,userId:u.id,amount,type:'BONUS',source:'promocode',metadata:{code,promoId:promo.id}}) }); return {code,amount:Number(amount),balance:Number(updated.balance)} })
 app.get('/promocode/list',{preHandler:[(app as any).authenticate]},async(req)=>{ const u=await getAuthUser(req); const promos=await prisma.walletTransaction.findMany({where:{userId:u.id,source:'promo-create'},orderBy:{createdAt:'desc'},take:50}); const items=[] as any[]; for(const promo of promos){ const meta:any=promo.metadata||{}; const used=await prisma.walletTransaction.count({where:{source:'promo-redeem',metadata:{path:['code'],equals:meta.code}} as any}); items.push({code:meta.code,amount:Number(meta.amount)||0,maxUses:Number(meta.maxUses)||1,used,remaining:Math.max(0,(Number(meta.maxUses)||1)-used),createdAt:promo.createdAt}); } return {items} })

}
