import { randomInt, randomFloat } from '../utils/random.js'
import { FastifyInstance } from 'fastify'
import { z } from 'zod'
import { prisma } from '../db.js'
import { getAuthUser } from '../auth/getUser.js'
import { applyBalanceChange } from '../wallet/wallet.js'
import { weeklyStats } from '../utils/weeklyStats.js'
import { checkChannelSubscription } from '../utils/telegram.js'
const promoCreateSchema=z.object({code:z.string().min(2).max(32),amount:z.number().int().positive().max(10000000),maxUses:z.number().int().positive().max(100000).default(1)})
const promoRedeemSchema=z.object({code:z.string().min(2).max(32)})
function norm(code:string){return code.trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'')}
const WHEEL_SEGMENTS=[{amount:100,weight:30},{amount:200,weight:25},{amount:300,weight:18},{amount:500,weight:12},{amount:750,weight:8},{amount:1000,weight:4},{amount:1500,weight:2},{amount:2500,weight:1}]
const WHEEL_COOLDOWN_MS=24*60*60*1000
function pickWheelSegment(){ const total=WHEEL_SEGMENTS.reduce((s,x)=>s+x.weight,0); let r=randomFloat()*total; for(let i=0;i<WHEEL_SEGMENTS.length;i++){ r-=WHEEL_SEGMENTS[i].weight; if(r<=0) return i } return WHEEL_SEGMENTS.length-1 }
const WHEEL_WEEKLY_WAGER=Number(process.env.WHEEL_WEEKLY_WAGER||100000)
// Доступ к Gamble Wheel: подписка на канал + сумма ставок за текущую неделю.
async function wheelRequirements(u:any){ const [stats,sub]=await Promise.all([weeklyStats(u.id),checkChannelSubscription(u.telegramId.toString())]); const wagerOk=stats.wagered>=WHEEL_WEEKLY_WAGER; return {ok:Boolean(sub.ok&&wagerOk),subscription:{ok:sub.ok,configured:sub.configured,channel:sub.channel,url:sub.url},wager:{ok:wagerOk,required:WHEEL_WEEKLY_WAGER,current:stats.wagered,remaining:Math.max(0,WHEEL_WEEKLY_WAGER-stats.wagered),weekStart:stats.weekStart,weekEnd:stats.weekEnd}} }
function wheelLockReason(req:any){ if(!req.subscription.ok) return 'Подпишитесь на канал '+(req.subscription.channel||'проекта')+', чтобы крутить колесо'; if(!req.wager.ok) return 'Сделайте ставок на '+req.wager.required.toLocaleString('ru-RU')+' GC за неделю: осталось '+req.wager.remaining.toLocaleString('ru-RU')+' GC'; return null }
export async function bonusRoutes(app:FastifyInstance){
 app.get('/wheel/status',{preHandler:[(app as any).authenticate]},async(req)=>{ const u=await getAuthUser(req); const requirements=await wheelRequirements(u); const fresh=await prisma.user.findUniqueOrThrow({where:{id:u.id}}); const last=(fresh as any).lastWheelSpinAt as Date|null; const nextAt=last?new Date(last.getTime()+WHEEL_COOLDOWN_MS):null; const cooldownReady=!nextAt||Date.now()>=nextAt.getTime(); return {ready:Boolean(cooldownReady&&requirements.ok),cooldownReady,locked:!requirements.ok,lockReason:wheelLockReason(requirements),nextAvailableAt:nextAt?nextAt.toISOString():null,requirements} })
 // Атомарный захват кулдауна: раньше проверка "последний спин" шла отдельным запросом
 // до транзакции, и два быстрых зараза могли оба проскочить проверку до того,
 // как любой из них усел записать время спина — так можно было крутить колесо несколько
 // раз подряд вместо одного раза в сутки. Теперь бронь кулдауна берётся одним
 // атомарным UPDATE ... WHERE в той же транзакции, что и начисление приза.
 app.post('/wheel',{preHandler:[(app as any).authenticate]},async(req,rep)=>{ const u=await getAuthUser(req); const requirements=await wheelRequirements(u); if(!requirements.ok) return rep.code(403).send({error:wheelLockReason(requirements),locked:true,requirements}); const idx=pickWheelSegment(); const amount=BigInt(WHEEL_SEGMENTS[idx].amount); const cutoff=new Date(Date.now()-WHEEL_COOLDOWN_MS); try{ const updated=await prisma.$transaction(async tx=>{ const claimed=await tx.$queryRawUnsafe(`UPDATE "User" SET "lastWheelSpinAt" = NOW() WHERE id = $1 AND ("lastWheelSpinAt" IS NULL OR "lastWheelSpinAt" <= $2) RETURNING "lastWheelSpinAt"`,u.id,cutoff) as any[]; if(!claimed.length) throw new Error('WHEEL_COOLDOWN'); return applyBalanceChange({tx,userId:u.id,amount,type:'BONUS',source:'wheel_spin',metadata:{segment:idx,prize:WHEEL_SEGMENTS[idx].amount}}) }); return {segment:idx,amount:Number(amount),balance:Number(updated.balance),nextAvailableAt:new Date(Date.now()+WHEEL_COOLDOWN_MS).toISOString()} }catch(e:any){ if(e.message==='WHEEL_COOLDOWN') return rep.code(400).send({error:'Колесо ещё не готово'}); throw e } })
 // Дневной бонус привязан к уникальному индексу (userId, dayKey): двойная активация в
 // одни сутки теряет создание с ошибкой P2002 вместо того, чтобы проскочить мимо
 // предварительную проверку, как это было раньше.
 app.post('/daily',{preHandler:[(app as any).authenticate]},async(req,rep)=>{ const u=await getAuthUser(req); const dayStart=new Date(); dayStart.setHours(0,0,0,0); const dayKey=dayStart.toISOString().slice(0,10); const amount=200n; try{ const updated=await prisma.$transaction(async tx=>{ await tx.dailyBonus.create({data:{userId:u.id,amount,dayKey}}); return applyBalanceChange({tx,userId:u.id,amount,type:'BONUS',source:'daily_bonus'}) }); return {amount:Number(amount),balance:Number(updated.balance)} }catch(e:any){ if(String(e?.code)==='P2002') return rep.code(400).send({error:'Daily bonus already claimed'}); throw e } })
 // Промокоды теперь хранятся в отдельных таблицах (PromoCode/PromoRedemption) вместо поиска
 // по metadata в WalletTransaction — это даёт настоящие уникальные индексы и атомарный CAS
 // на лимит активаций, так что параллельные запросы больше не могут выдать больше GC,
 // чем было зарезервировано создателем, и один игрок не может активировать один код дважды.
 app.post('/promocode/create',{preHandler:[(app as any).authenticate]},async(req,rep)=>{ const u=await getAuthUser(req); const parsed=promoCreateSchema.safeParse(req.body); if(!parsed.success) return rep.code(400).send({error:'Введите код и сумму'}); const code=norm(parsed.data.code); if(!code) return rep.code(400).send({error:'Введите код промокода'}); const total=BigInt(parsed.data.amount*parsed.data.maxUses); try{ await prisma.$transaction(async tx=>{ await applyBalanceChange({tx,userId:u.id,amount:-total,type:'ADMIN_ADJUSTMENT',source:'promo-create-reserve',metadata:{code,amount:parsed.data.amount,maxUses:parsed.data.maxUses}}); await tx.promoCode.create({data:{code,amount:BigInt(parsed.data.amount),maxUses:parsed.data.maxUses,creatorId:u.id,creatorUsername:u.username||null}}) }) }catch(e:any){ if(String(e?.code)==='P2002') return rep.code(400).send({error:'Такой промокод уже есть'}); if(e.message==='Insufficient balance') return rep.code(400).send({error:'Недостаточно Gamble Coin'}); throw e } return {code,amount:parsed.data.amount,maxUses:parsed.data.maxUses} })
 app.post('/promocode/redeem',{preHandler:[(app as any).authenticate]},async(req,rep)=>{ const u=await getAuthUser(req); const parsed=promoRedeemSchema.safeParse(req.body); if(!parsed.success) return rep.code(400).send({error:'Введите промокод'}); const code=norm(parsed.data.code); const promo=await prisma.promoCode.findUnique({where:{code}}); if(!promo) return rep.code(404).send({error:'Промокод не найден'}); const amount=promo.amount; if(amount<=0n) return rep.code(400).send({error:'Промокод недействителен'}); try{ const updated=await prisma.$transaction(async tx=>{ await tx.promoRedemption.create({data:{code,userId:u.id,amount}}); const claim=await tx.$queryRawUnsafe(`UPDATE "PromoCode" SET "usedCount" = "usedCount" + 1 WHERE code = $1 AND "usedCount" < "maxUses" RETURNING "usedCount"`,code) as any[]; if(!claim.length) throw new Error('PROMO_LIMIT'); return applyBalanceChange({tx,userId:u.id,amount,type:'BONUS',source:'promocode',metadata:{code,promoId:promo.id}}) }); return {code,amount:Number(amount),balance:Number(updated.balance)} }catch(e:any){ if(e.message==='PROMO_LIMIT') return rep.code(400).send({error:'Лимит активаций закончился'}); if(String(e?.code)==='P2002') return rep.code(400).send({error:'ты уже активировал этот промокод'}); throw e } })
 app.get('/promocode/list',{preHandler:[(app as any).authenticate]},async(req)=>{ const u=await getAuthUser(req); const promos=await prisma.promoCode.findMany({where:{creatorId:u.id},orderBy:{createdAt:'desc'},take:50}); return {items:promos.map(p=>({code:p.code,amount:Number(p.amount),maxUses:p.maxUses,used:p.usedCount,remaining:Math.max(0,p.maxUses-p.usedCount),createdAt:p.createdAt}))} })

}
